# Generated by Django 3.2.8 on 2022-01-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='view_d',
            new_name='Materia',
        ),
    ]
