# Generated by Django 3.2.8 on 2022-01-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0002_rename_view_d_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='materia',
            new_name='nome',
        ),
    ]
