# Generated by Django 3.2.8 on 2022-01-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0003_rename_materia_materia_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Studente',
                'verbose_name_plural': 'Studenti',
            },
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materia'},
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.FloatField()),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materie', to='prova_pratica_1.materia')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenti2', to='prova_pratica_1.studente')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Voti',
            },
        ),
        migrations.CreateModel(
            name='Assenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oreAssenza', models.BigIntegerField()),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenti3', to='prova_pratica_1.studente')),
            ],
            options={
                'verbose_name': 'Assenza',
                'verbose_name_plural': 'Assenze',
            },
        ),
    ]
