# Generated by Django 3.2.8 on 2022-01-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0005_auto_20220127_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assenza',
            name='studente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assenze', to='prova_pratica_1.studente'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='studente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='prova_pratica_1.studente'),
        ),
    ]
