# Generated by Django 3.2.8 on 2022-01-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0006_auto_20220127_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='materie',
            new_name='materia',
        ),
    ]
