# Generated by Django 3.2.8 on 2022-01-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0007_rename_materie_voto_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='assenza',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assenze', to='prova_pratica_1.materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='prova_pratica_1.materia'),
        ),
    ]
